import Head from 'next/head'
import { Avatar } from '@material-ui/core'
import { StylesProvider } from '@material-ui/styles'
import styled from 'styled-components'

const StyledAvatar = styled(Avatar)`
    background: purple;
    color: ivory;
    margin: 20px;
    &:hover {
      background-color: #5469d4;
      color: #fff;
`

const StyledH1 = styled.h1`
      color: green;
      font-size: 36px;
      font-weight: bold;
`
export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StylesProvider injectFirst>
          <main className="main">
            <h1>Hello World</h1>
            <StyledH1>Hello World</StyledH1>
            <Avatar><span>CK</span></Avatar>
            <StyledAvatar><span>CK</span></StyledAvatar>
          </main>
      </StylesProvider>
    </div>
  )
}
